medical_history/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),


]

medical_history/admins/urls.py
from django.urls import path
from . import views

app_name = 'admins'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_patient/', views.add_patient, name='add_patient'),
    path('add_physician/', views.add_doc, name='add_doc'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('patients/', views.get_patients, name='get_patients'),
    path('physicians/', views.get_docs, name='get_docs'),
    path('feedback/', views.get_feedbacks, name='get_feedbacks'),
    path('medical_records/', views.get_records, name='get_records'),
    path('health_facilities/', views.get_facilities, name='get_facilities'),







]

medical_history/medical_history/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django import urls
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    # overriding the default redirecting of admin after logout REMEMBER This always comes before admin.site.urls
    path('admin/logout/', views.logout),
    path('admins/', include('admins.urls', namespace='admins')),
    path('admin/', admin.site.urls),
    path('patient/', include('patient.urls', namespace='patient')),
    path('', include('accounts.urls', namespace='accounts')),
    path('feedback/', include('feedback.urls', namespace='feedback'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

medical_history/patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('details/', views.get_patient, name='get_patient'),
    path('details/record=<int:record_id>', views.get_record, name='get_record'),
    path('details/main/patient=<int:id>',
         views.get_patient_back, name='get_patient_back'),
    path('record', views.enter_record, name='enter_record'),
    path('add/', views.add_patient, name='add_patient'),
]

medical_history/accounts/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from facilities.models import Facility

# Create your models here.


class HealthOfficer(models.Model):
    titles = (
        ('Medical Oficer', 'Medical Officer'),
        ('Consultant', 'Consultant'),
        ('Surgeon', 'Surgeon'),
        ('Neural Surgeon', 'Neural Surgeon'),
        ('Gynaecologist', 'Gynaecologist'),
        ('ENT Expert', 'ENT Expert'),
        ('Paediatric', 'Paediatric'),
        ('Psychiatrist', 'Psychiatrist'),
        ('Clinical Officer', 'Officer'),
        ('Cardiologist', 'Cardiologist'),
        ('Other', 'Other')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id_number = models.CharField(max_length=10, unique=True)
    reg_number = models.CharField(max_length=100, primary_key=True)
    title = models.CharField(max_length=100, choices=titles)
    facility = models.ForeignKey(Facility, on_delete=models.DO_NOTHING)
    phone = models.CharField(max_length=10)
    email = models.EmailField()
    pic = models.ImageField(
        blank=True, upload_to='media/officers/%Y/%m/%d', help_text='Health officers Profile Pic')

    def __str__(self) -> str:
        return self.reg_number

    class Meta:
        db_table = 'health_officers'
        ordering = ('reg_number',)
        verbose_name_plural = 'health_officers'

medical_history/accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from .models import HealthOfficer
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from .models import HealthOfficer
from django.contrib.auth.models import User

# Create your views here.


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:

            auth.login(request, user)

            messages.success(request, 'You are Logged in Welcome ')
            if username == 'admin':
                return redirect('admins:index')

            else:

                return redirect('accounts:dashboard')
        else:
            messages.error(request, 'Invalid Credentials')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html', )


@login_required
def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        messages.success(request, 'You are Logged out')

    return redirect('accounts:login')


@login_required
def dashboard(request):
    user_id = request.user.id
    this_user = get_object_or_404(User, pk=user_id)
    officer = get_object_or_404(HealthOfficer, user=this_user)
    context = {'officer': officer, }
    return render(request, 'accounts/officers_dashboard.html', context)

medical_history/templates/accounts/dashboard_base.html
<!DOCTYPE html>
{%load static%}
{%load humanize%}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Patient's Medical Records System {%block title%}{%endblock%}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'themes/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'themes/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Top Bar -->
{%include 'partials/_topbar.html'%}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center nav-item active"
                href="{%url 'accounts:dashboard'%}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span class="sidebar-brand-text"> Dashboard </span>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Pages Collapse Menu -->
            <div class="m-2">
                <img class="rounded-circle" src="{{officer.pic.url}}" alt="" height="200px" width="" />

            </div>
            <!-- Nav Item - Utilities Collapse Menu -->
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="text-light">
                <p>
                    <i class="fas fa-fw fa-user"></i>
                    {{officer.user.first_name|title}} {{officer.user.last_name|title}}
                </p>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Nav Item - Charts -->
            <li class="text-light">
                <p>
                    <i class="fas fa-fw fa-hospital"></i>
                    {{officer.title|title}}
                </p>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Nav Item - Tables -->
            <li class="text-light">
                <p>
                    <i class="fas fa-fw fa-home"></i>
                    {{officer.facility|title}}, {{officer.facility.facility_level|title}}
                </p>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <li class="text-light">
                <p>
                    <i class="fas fa-fw fa-globe"></i>
                    {{officer.facility.county|title}} County
                </p>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

            <!-- Topbar Navbar -->
            {%include 'partials/_navbar.html'%}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    {%include 'partials/_alerts.html'%}
                    {%block content%}{%endblock%}

                    <!--DATA TABLES GOES HERE-->

                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- FOOTER -->
            {%include 'partials/_footer.html'%}

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Thankyou for spending quality time on our system.<br><br>

                Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{%url 'accounts:logout'%}">Logout</a>
            </div>
        </div>
    </div>
</div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'themes/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'themes/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'themes/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'themes/js/sb-admin-2.min.js ' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'themes/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'themes/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'themes/js/demo/chart-pie-demo.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

medical_history/templates/accounts/login.html
{%extends 'base.html'%}
<!--static-->
{%load static%}
<!---->
{%block title%} | Account Login{%endblock%}
<!--body-->
{%block content%}

<section id="login" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card bg-success">
                    {%include 'partials/_alerts.html'%}

                    <div class="card-header text-white text-center">
                        <img src="{%static 'img/mlogo.png'%}" width="200" height="200" alt="" />
                        <br />
                        <h3 class="d-inline align-middle">Please Login Here</h3>
                    </div>
                    <div class="card-body">
                        <form action="{%url 'accounts:login'%}" method="post">
                            {%csrf_token%}
                            <div class="form-group">
                                <label for="username">Registration Number</label>
                                <input type="text" name="username" class="form-control" placeholder="Enter Your Registration Number Here" required />
                            </div>

                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" class="form-control"  placeholder="Enter Your ID" required />
                            </div>

                            <input type="submit" value="Login" class="btn btn-outline-primary btn-block " />
                        </form>
                    
                    </div>

                    <div class="card-footer">
                        <a href="" class="text-danger">Forgot Password?</a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</section>

{%endblock%}

medical_history/templates/accounts/officers_dashboard.html
{%extends 'accounts/dashboard_base.html'%}
{%block title%} | Health Officer's Dashboard {%endblock%}
{%block content%}

    <section id="register" class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header bg-primary text-white text-center">
                            <h4>
                                <i class="fas fa-search"></i> Enter Patient's HUDUMA ID to Search
                            </h4>
                        </div>
                        <div class="card-body ">
                            <form method="POST" action="{%url 'patient:get_patient'%}">
                                {%csrf_token%}
                                <div class="form-group">
                                    <label for="huduma_id" class="text-danger">Huduma ID Number:</label>
                                    <input type="number" name="huduma_id" class="form-control text-sm is-valid" placeholder="Enter Huduma ID here" required>
                                </div>
                                <input type="submit" value="Search For Patient's Records" class="btn btn-success btn-block">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{%endblock%}

medical_history/templates/accounts/success.html
{%extends 'base2.html'%}
<!--title-->
{%block title%}|Record entered{%endblock%}
<!--active-->
{%block active%}Record entered Successfully{%endblock%}
<!--block content-->
{%block content%}
<div class="container">
    <div class="row py-5">
        <div class="col">
            <div class="card text-center badge-primary">
                <div class="card-header display-1">
                    <h2><u>Record Entered Successfully </u></h2>
                </div>
                <div class="card-body">
                    <div class="card-text lead">
                        You made a new record about the patient successfully.

                        <p class="display-3">
                            Thankyou for Serving this nation competently.We truly treasure you
                        </p>
                    </div>
                    <a class="btn btn-outline-success btn-block" href="{%url 'accounts:dashboard'%}">Back Home</a>
                </div>
                <hr />
            </div>
        </div>
    </div>
</div>
{%endblock%}