medical_history/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),


]

medical_history/admins/urls.py
from django.urls import path
from . import views

app_name = 'admins'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_patient/', views.add_patient, name='add_patient'),
    path('add_physician/', views.add_doc, name='add_doc'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('patients/', views.get_patients, name='get_patients'),
    path('physicians/', views.get_docs, name='get_docs'),
    path('feedback/', views.get_feedbacks, name='get_feedbacks'),
    path('medical_records/', views.get_records, name='get_records'),
    path('health_facilities/', views.get_facilities, name='get_facilities'),







]

medical_history/feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('add/', views.add_feedback, name='add_feedback'),
]

medical_history/medical_history/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django import urls
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    # overriding the default redirecting of admin after logout REMEMBER This always comes before admin.site.urls
    path('admin/logout/', views.logout),
    path('admins/', include('admins.urls', namespace='admins')),
    path('admin/', admin.site.urls),
    path('patient/', include('patient.urls', namespace='patient')),
    path('', include('accounts.urls', namespace='accounts')),
    path('feedback/', include('feedback.urls', namespace='feedback'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

medical_history/patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('details/', views.get_patient, name='get_patient'),
    path('details/record=<int:record_id>', views.get_record, name='get_record'),
    path('details/main/patient=<int:id>',
         views.get_patient_back, name='get_patient_back'),
    path('record', views.enter_record, name='enter_record'),
    path('add/', views.add_patient, name='add_patient'),
]

medical_history/patient/models.py
from accounts.models import HealthOfficer
from django.db import models
from django.db.models.fields import DateField
from facilities.models import Facility


class PatientBio(models.Model):

    counties = (
        ('Mombasa', 'Mombasa'),
        ('Kwale', 'Kwale'),
        ('Kilifi', 'Kilifi'),
        ('Tana River', 'Tana River'),
        ('Lamu', 'Lamu'),
        ('Taita Taveta', 'Taita Taveta'),
        ('Garissa', 'Garissa'),
        ('Wajir', 'Wajir'),
        ('Mandera', 'Mandera'),
        ('Marsabit', 'Marsabit'),
        ('Isiolo', 'Isiolo'),
        ('Meru', 'Meru'),
        ('Tharaka Nithi', 'Tharaka Nithi'),
        ('Embu', 'Embu'),
        ('Kitui', 'Kitui'),
        ('Machakos', 'Machakos'),
        ('Makueni', 'Makueni'),
        ('Nyandarua', 'Nyandarua'),
        ('Nyeri', 'Nyeri'),
        ('Kirinyaga', 'Kirinyaga'),
        ("Murang'a", "Murang'a"),
        ('Kiambu', 'Kiambu'),
        ('Turkana', 'Turkana'),
        ('West Pokot', 'West Pokot'),
        ('Samburu', 'Samburu'),
        ('Trans-Nzoia', 'Trans-Nzoia'),
        ('Uasin Gishu', 'Uasin Gishu'),
        ('Elgeyo Marakwet', 'Elgeyo Marakwet'),
        ('Nandi', 'Nandi'),
        ('Baringo', 'Baringo'),
        ('Laikipia', 'Laikipia'),
        ('Nakuru', 'Nakuru'),
        ('Narok', 'Narok'),
        ('Kajiado', 'Kajiado'),
        ('Kericho', 'Kericho'),
        ('Bomet', 'Bomet'),
        ('Kakamega', 'Kakamega'),
        ('Vihiga', 'Vihiga'),
        ('Bungoma', 'Bungoma'),
        ('Busia', 'Busia'),
        ('Siaya', 'Siaya'),
        ('Kisumu', 'Kisumu'),
        ('Homa Bay', 'Homa Bay'),
        ('Migori', 'Migori'),
        ('Kisii', 'Kisii'),
        ('Nyamira', 'Nyamira'),
        ('Nairobi', 'Nairobi'),

    )
    genders = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )
    huduma_id = models.CharField(max_length=100, primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    #other_name = models.CharField(max_length=50)
    dob = models.DateField()
    phone = models.CharField(
        max_length=10, help_text='for infants, enter gurdians/parents phone')
    #email = models.EmailField(blank=True)
    gender = models.CharField(
        max_length=50,  choices=genders)
    #location = models.CharField(max_length=100)
    #constituency = models.CharField(max_length=100)
    county = models.CharField(max_length=50, choices=counties)
   # pic = models.ImageField(
   #     blank=True, upload_to='media/patients/profile_pics/%Y/%m/%d', help_text="Patient's Profile Pic")

    def __str__(self) -> str:
        return self.huduma_id

    class Meta:
        db_table = 'patientbio'
        ordering = ('dob',)
        verbose_name_plural = 'patientbio'


class Patient(models.Model):
    patient = models.ForeignKey(PatientBio, on_delete=models.CASCADE)
    facility = models.ForeignKey(Facility, on_delete=models.DO_NOTHING)
    health_officer = models.ForeignKey(
        HealthOfficer, on_delete=models.DO_NOTHING)
    date = models.DateField(
        auto_now_add=True, help_text='The Date this Record was made')
    presenting_symptoms = models.TextField()
    lab_works = models.TextField()
    diagnosis_made = models.TextField()
    treatment_offered = models.TextField()
    comment = models.TextField()
    x_ray = models.ImageField(
        blank=True, upload_to='media/patients/x_rays/%Y/%m/%d', help_text="Patient's Profile Pic")
    # other_docs HERE ATTACH ANY OTHER RELEVANT DOCUMENTS
    docs = models.FileField(
        blank=True, upload_to='media/patients/treatment documents/%Y/%m/%d', help_text="Treatment Support Documents")

    class Meta:
        db_table = 'patientinfo'
        ordering = ('date',)
        verbose_name_plural = 'patientinfo'

    def __str__(self) -> str:
        return str(self.id)

medical_history/patient/views.py
from django.contrib import auth, messages
from facilities.models import Facility
from accounts.models import HealthOfficer
from .models import PatientBio, Patient
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import Patient, PatientBio
from django.contrib.auth.decorators import login_required
from .counties import Counties, Genders
from django.contrib.auth.models import User


@login_required
def get_patient(request):
    if request.method == 'POST':
        huduma_id = request.POST['huduma_id']

        patients = PatientBio.objects.filter(huduma_id=huduma_id)[:1]

        details = Patient.objects.filter(patient=huduma_id).order_by('-date')

        genders = Genders
        counties = Counties

        return render(request, 'patient/patient_records.html', {'patients': patients, 'details': details, 'counties': counties, 'genders': genders})


@login_required
def get_patient_back(request, id):
    patients = PatientBio.objects.order_by(
        'huduma_id').filter(huduma_id=id)[:1]
    details = Patient.objects.filter(patient=id).order_by('-date')
    genders = Genders
    counties = Counties
    huduma_id = id
    return render(request, 'patient/patient_records.html', {'patients': patients, 'details': details, 'counties': counties, 'genders': genders, 'huduma_id': huduma_id})


@login_required
def get_record(request, record_id):
    record = get_object_or_404(Patient, pk=record_id)

    genders = Genders
    counties = Counties
    context = {
        'record': record, 'genders': genders, 'counties': counties
    }

    return render(request, 'patient/more_details.html', context)


@login_required
def enter_record(request):
    if request.method == 'POST':
        huduma_id = request.POST['huduma_id']
        officer = request.POST['officer']
        symptoms = request.POST['symptoms']
        lab_works = request.POST['lab_works']
        diagnosis = request.POST['diagnosis']
        treatment = request.POST['treatment']
        comment = request.POST['comment']
        docs = request.FILES['documents']
        x_ray = request.FILES['x_ray']

        this_user = get_object_or_404(User, username=officer)
        this_officer = get_object_or_404(HealthOfficer, user=this_user)
        this_patient = get_object_or_404(PatientBio, huduma_id=huduma_id)
        this_faciilty = this_officer.facility

        this_record = Patient.objects.create(patient=this_patient, facility=this_faciilty, health_officer=this_officer, presenting_symptoms=symptoms,
                                             lab_works=lab_works, diagnosis_made=diagnosis, treatment_offered=treatment, comment=comment, x_ray=x_ray, docs=docs)

        this_record.save()
        #messages.success(request, 'Record entered Successfully')

        return render(request, 'accounts/success.html')


def add_patient(request):
    if request.method == 'POST':
        huduma_id = request.POST['huduma_id']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        gender = request.POST['gender']
        dob = request.POST['dob']
        phone = request.POST['phone']
        county = request.POST['county']

        if PatientBio.objects.filter(huduma_id=huduma_id).exists():
            messages.error(
                request, "This Patient is Already in the System!")
            return redirect('accounts:dashboard')
        else:

            this_patient = PatientBio.objects.create(
                huduma_id=huduma_id, first_name=first_name, last_name=last_name, dob=dob, phone=phone, gender=gender, county=county)

            this_patient.save()
            messages.success(request, 'Patient added Successfully')

            return redirect('accounts:dashboard')

medical_history/templates/patient/base.html
<!DOCTYPE html>
{%load static%}
{%load humanize%}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Patient's Medical Records System {%block title%}{%endblock%}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'themes/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'themes/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'themes/vendor/datatables/dataTables.bootstrap4.min.css'%}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Top Bar -->
{%include 'partials/_topbar.html'%}
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

            <!-- Topbar Navbar -->
            {%include 'partials/_navbar.html'%}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    {%include 'partials/_alerts.html'%}
                    {%block content%}{%endblock%}

                    <!--DATA TABLES GOES HERE-->

                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- FOOTER -->
            {%include 'partials/_footer.html'%}

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Thankyou for saving lives. You are invaluable. <br><br>
                    
                    Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{%url 'accounts:logout'%}">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'themes/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'themes/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'themes/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'themes/js/sb-admin-2.min.js ' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'themes/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'themes/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'themes/js/demo/chart-pie-demo.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'themes/vendor/datatables/jquery.dataTables.min.js'%}"></script>
    <script src="{%static 'themes/vendor/datatables/dataTables.bootstrap4.min.js'%}"></script>
    
    <!-- Page level custom scripts -->
    <script src="{% static 'themes/js/demo/datatables-demo.js'%}"></script>

</body>
</html>

medical_history/templates/patient/more_details.html
{%extends 'patient/base.html'%}
<!--main-->
{%load static%}
<!--main-->
{%load humanize%}
<!--main-->
{%block title%} | More Details {%endblock%}
<!--main-->
{%block content%}
<!--math filters-->
{%load mathfilters%}

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{%url 'patient:get_patient_back' record.patient.huduma_id %}">Go Back to Records Main Page</a>
                </li>
                
                <li class="breadcrumb-item active">{{record.patient.first_name}} {{record.patient.last_name}}'s Record Number {{record.id}} </li>
            </ol>
        </nav>
    </div>
</section>

<!-- Alerts -->

{%include 'partials/_alerts.html'%}

<section id="dashboard" class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-info">
                        <h4 class="text-center text-white ">Record Number: {{record.id}} for {{record.patient.first_name}} {{record.patient.last_name}} </h4>
                    </div>
                    <table class="table table-striped">
                        <thead>
                            <tr class="text-danger">
                                <th scope="row">PARTICULARS</th>
                                <th scope="row">VALUES</th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="text-info">Date of this Treatment</td>
                                <td>{{record.date}}</td>
                            </tr>
                            <tr>
                                <td class="text-info">Presenting Symptoms</td>
                                <td>{{record.presenting_symptoms|title}}</td>

                            </tr>
                            <tr>
                                <td class="text-info">Lab Tests</td>
                                <td>{{record.lab_works|title}}</td>
                            </tr>
                            <tr>
                                <td class="text-info">Diagnosis Made</td>
                                <td>{{record.diagnosis_made|title}}</td>

                            </tr>
                            <tr>
                                <td class="text-info">Treatment Given</td>
                                <td>{{record.treatment_offered|title}}</td>

                            </tr>
                            <tr>
                                <td class="text-info">Health Practioner's Comment</td>
                                <td>{{record.comment|title}}</td>
                            
                            </tr>

                            <tr>
                                <td class="text-info">Relevant Documents <small>e.g x-rays and other support docs</small></td>
                                <td>{{record.docs|title}}</td>
                            
                            </tr>
                            
                            <tr>
                                <td colspan="2" class="text-dark text-center"><h2>Other Details</h2></td>
                                
                            
                            </tr>
                            <tr>
                                <td class="text-info">Health Facility Visited</td>
                                <td>{{record.facility|title}}</td>

                            </tr>
                            <tr>
                                <td class="text-info">Health Facility Level</td>
                                <td>{{record.facility.facility_level|upper}}</td>

                            </tr>
                            <tr>
                                <td class="text-info">Intervening Health Practioner </td>
                                <td>{{record.health_officer.title|title}}. {{record.health_officer.user.first_name|title}} {{record.health_officer.user.last_name|title}}</td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

<div class="mt-5">
    <p class="text-danger text-center">You feel the treatment offered to this patient wasn't worth? </p>
        
     <p class="text-danger text-center">  Please let us know </p>
    
  <p class="text-danger text-center"> <a href="" data-toggle="modal" data-target="#feedbackModal">Report Here</a> </p>
    
  <p class="small text-dark text-center">Help us achieve sanity in the Health sector</p>
</div>
</section>
<!--ADDING NEW RECORD-->
<div class="row">
    <div class="col-md-12">
        <span class="text-center btn btn-primary btn-block" data-toggle="modal" data-target="#enterRecord">
            PLEASE RECORD ABOUT TODAY'S TREATMENT HERE
        </span>
    </div>
</div>





<!-- FEEDBACK Modal -->
<div class="modal fade" id="feedbackModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" >Report a purported Patient Mistreatment</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">

                            <small class="text-danger">NOTE:  The information given here-in can be used in a court of law <br><br>
                                Nevertheless, we will keep you anonymous as we investigate over this matter.<br><br>
                                PLEASE BE HONEST</small>

                <form action="{%url 'feedback:add_feedback'%}" method="POST">
                    {% csrf_token %}
                    <!--GET THIS MEDIC's ID -->
                    <input type="hidden" name="record" value="{{record.id}}">
                    <input type="hidden" name="officer" value="{{user}}">
                    <div class="form-group">
                        <label for="email" class="col-form-label" >Your Email:</label>
                        <input type="email" name="email" class="form-control" value="{{user.email}}"  readonly required>
                    </div>
                    <!--Category of the matter(mistreatment)-->
                    <div class="form-group">
                        <label for="message" class="col-form-label">Why Do you think this patient was mistreated? (please explain)</label>
                        <textarea name="message" class="form-control" required></textarea>
                    </div>
                    <hr>
                    <input type="submit" value="Send Feedback" class="btn btn-block btn-success">
                </form>
            </div>
        </div>
    </div>
</div>



<!-- ADD RECORD MODAL -->
<div class="modal fade" id="enterRecord">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white text-center">
                <h5 class="modal-title text-center">Document About today's treatment here</h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{%url 'patient:enter_record' %}" method="POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    <input type="hidden" name="officer" value="{{user}}">
                    <div class="form-group">
                        <label for="name" class="col-form-label">Huduma ID Number</label>
                        <input type="text" class="form-control" name="huduma_id" value="{{record.patient.huduma_id}}" readonly required />
                    </div>
                    <div class="form-group">
                        <label for="symptoms" class="col-form-label">Presenting Symptoms</label>
                        <input type="text" class="form-control" name="symptoms" required />
                    </div>
                    <div class="form-group">
                        <label for="lab_works" class="col-form-label">Lab Work Performed</label>
                        <input type="text" class="form-control" name="lab_works" required />
                    </div>
                    <div class="form-group">
                        <label for="diagnosis" class="col-form-label">Diagnosis Made</label>
                        <input type="text" class="form-control" name="diagnosis" required />
                    </div>
                    <div class="form-group">
                        <label for="treatment" class="col-form-label">Treatment Offered</label>
                        <input type="text" class="form-control" name="treatment" required />
                    </div>

                    <div class="form-group">
                        <label for="comment" class="col-form-label">Comments</label>
                        <textarea name="comment" class="form-control" id="" cols="30" rows="5"></textarea>
                    </div>

                    <div class="form-group">
                        <label for="documents"class="col-form-label">Attach Any Relevant Document:</label> 
                        <small class="text-danger">Attach relevant documents e.g lab reports, consultant reports, x_ray reports, etc</small>
                        <input type="file" class="form-control" name="documents" >
                    </div>

                    <div class="form-group">
                        <label for="x_ray"class="col-form-label">X_ray Film:</label>
                        <small class="text-primary">Attach X_rays image films (if Any)</small>
                        <input type="file" class="form-control" name="x_ray">
                    </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary btn-block" type="submit">Add Treatment Record to Repository</button>
                </form>
            </div>
        </div>
    </div>
</div>

{%endblock%}