medical_history/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),


]

medical_history/admins/urls.py
from django.urls import path
from . import views

app_name = 'admins'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_patient/', views.add_patient, name='add_patient'),
    path('add_physician/', views.add_doc, name='add_doc'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('patients/', views.get_patients, name='get_patients'),
    path('physicians/', views.get_docs, name='get_docs'),
    path('feedback/', views.get_feedbacks, name='get_feedbacks'),
    path('medical_records/', views.get_records, name='get_records'),
    path('health_facilities/', views.get_facilities, name='get_facilities'),







]

medical_history/medical_history/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django import urls
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    # overriding the default redirecting of admin after logout REMEMBER This always comes before admin.site.urls
    path('admin/logout/', views.logout),
    path('admins/', include('admins.urls', namespace='admins')),
    path('admin/', admin.site.urls),
    path('patient/', include('patient.urls', namespace='patient')),
    path('', include('accounts.urls', namespace='accounts')),
    path('feedback/', include('feedback.urls', namespace='feedback'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

medical_history/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css'%}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- lightbox-->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css'%}">
    <title>Patient's Medical Records System {%block title%}{%endblock%}</title>
</head>

<body>


    <section class="main">
        {% block content %}{%endblock%}
    </section>

    <script src="{% static 'js/jquery-3.3.1.min.js'%} "></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%} "></script>
    <script src="{% static 'js/lightbox.min.js'%} "></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

medical_history/templates/base2.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css'%}" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}" />
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}" />
    <!-- lightbox-->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css'%}" />
    <title>Patient's Medical Records System {%block title%}{%endblock%}</title>
</head>

<body id="page-top">
    <!-- Top Bar -->
    <section id="top-bar" class="p-3 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <i class="fas fa-phone"></i> (+254)-555-5555
                </div>
                <div class="col-md-4">
                    <i class="fas fa-envelope-open"></i> contact@medicals.com
                </div>
                <div class="col-md-4">
                    <div class="social text-right">
                        <a href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-facebook"></i>
                        </a>

                        <a href="#">
                            <i class="fab fa-whatsapp"></i>
                        </a>

                        <a href="#">
                            <i class="fab fa-linkedin"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <nav class="navbar navbar-expand-sm navbar-dark bg-success top">
        <div class="container">
            <a href="{%url 'accounts:dashboard'%}" class="navbar-brand">
                <img src="{%static 'img/mlogo.png'%}" width="100" height="100" alt="" />
            </a>

            <div class="row text-center">
                <div class="col-md-12 ">
                    <h1>Patient's Medical Records System</h1>
                   {%block caption%}  {%endblock%}
                </div>
            </div>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                <a href="{%url 'accounts:logout'%}" class="nav-link">
                <i class="fas fa-user-times"></i> Logout
                </a>
                </li>
                </ul>
            </div>
        </div>
    </nav>
   
    <section class="main">
        {% block content %}{%endblock%}
    </section>

    <!-- FOOTER -->
    <footer id="main-footer" class="bg-info text-white mt-5 p-5">
        <div class="container">
            <div class="row">
                <div class="col">
                    <p class="lead text-center">
                        Copyright &copy;
                        <span id="year"></span>
                        Patient's Medical Records System
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/jquery-3.3.1.min.js'%} "></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%} "></script>
    <script src="{% static 'js/lightbox.min.js'%} "></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

medical_history/templates/base3.html
<!DOCTYPE html>
{%load static%}
{%load humanize%}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Patient's Medical Records System {%block title%}{%endblock%}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'themes/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'themes/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Top Bar -->
    {%include 'partials/_topbar.html'%}



    <section class="text-white bg-success">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-md-4">
                    <a href="{%url 'admins:index'%}" class="navbar-brand">
                        <img src="{%static 'img/mlogo.png'%}" width="100" height="100" alt="" /> 
                    </a>
                    <sub class="lead">Patient's Medical Records System</sub>
                </div>
                
                <div class="col-md-6">
                    
                    <h1 class="display-4">Admin's Dashboard</h1>
                    <p class="lead">Management Page </p>
                </div>
                <div class="col-md-2">

                    <a class="nav-link dropdown-toggle" href="#" data-toggle="modal" data-target="#logoutModal">
                        <span class="ml-5 text-white">
                            <i class="fas fa-sign-out-alt ml-5"></i>LOGOUT</span>
                    </a>
                </div>
            </div>
        </div>
    </section>

   
<!-- End of Topbar -->

    <!-- Begin Page Content -->
    <div class="container-fluid">

    {%include 'partials/_alerts.html'%}
    {%block content%}{%endblock%}

    <!--DATA TABLES GOES HERE-->

    </div>
    <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->
    <!-- FOOTER -->
    {%include 'partials/_footer.html'%}

    </div>
    <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Thankyou for spending quality time on our system.<br><br>

                    Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{%url 'accounts:logout'%}">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'themes/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'themes/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'themes/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'themes/js/sb-admin-2.min.js ' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'themes/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'themes/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'themes/js/demo/chart-pie-demo.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>